spring:
  application:
    name: spring-cloud-nacos-sample-provider
  cloud:
    nacos:
      discovery:
        server-addr: http://152.136.119.254:8848
dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: spring-cloud://152.136.119.254
  scan:
    base-packages: harper.github.io